### PR TITLE
Add coverage support

### PR DESCRIPTION
**Pull request by muryanto1**
Add coverage support -- with this support, we can run run_tests.py with -c option.
TestRunnerBase.py expects tests/coverage.json in the repo where test suite resides.
tests/coverage.json lists the package name(s) that we want to get coverage on.

### CODE REVIEW

**Review by doutriaux1 — APPROVED** [review]
@muryanto1 sorry I could have sworn I already reviewed this! Looks good.

**Comment by doutriaux1** [comment]
@muryanto1 actually one comment, we should add a test in the test suite to test coverage and show the coverage of this repo.

**Comment by doutriaux1** [comment]
The test would be a good example for other repo as well.

**Comment by muryanto1** [comment]
Charles,  changes are ready for code review.
Changes include:
+ support for running run_tests.py with "-c <test coverage. json>"
+ add test tests/test_tr.py
+ update .circleci/config.yml to run tests with coverage for Linux py3 only.
+ update .circleci/config.yml to create conda env for py2, run tests for py2, only if it passes, then it proceeds to do the same for py3.

**Comment by doutriaux1** [comment]
thanks @muryanto1 will review today or tomorrow

**Comment by muryanto1** [comment]
I just noticed...I think in .circleci/config.yml's conda_upload, I need to do:
```
if [ $PY_VER = 'py2' ] then
       conda build $PKG_NAME -c cdat/label/nightly -c conda-forge -c cdat --python=2.7
else
       conda build $PKG_NAME -c cdat/label/nightly -c conda-forge -c cdat --python=3.6
fi

**Review by doutriaux1 — COMMENTED** [review]
@muryanto1 follwing our new PR process, we should add a doc directory with an example on how to run run_test.py with coverage.  I see it in the config.yml but user will not look there

**Review by doutriaux1 — CHANGES_REQUESTED** [review]
Also I just tested on another repo if you run with  `-c file.json` it will complain but only after downloading the sample_data, we might want to check first.
Also in the docs we should describe what the coverage,json file should look like.

**Review by doutriaux1 — COMMENTED** [review]
If running in env w/o coverage it does complain but keeps going, we should probably test for this and exit properly.

**Review by doutriaux1 — APPROVED** [review]
Lina, I think we are good to go. Thanks for the README. Feel free to merge into master.

**Pull request merged**
