### PR TITLE
first pass

### LINKED ISSUE #10: branch checkout does not exit nicely if branch does not exists
in vcs we're checkout the matching branch for baselines, but if that branch does not exists it fails the test suite right away see: https://circleci.com/gh/CDAT/vcs/936?utm_campaign=build-failed&utm_medium=email&utm_source=notification

Error message is:
```
Already up-to-date.
BRANCH WE ARE TRYING TO CHECKOUT is (boxfill_widgets_jupyter)
Executing git checkout boxfill_widgets_jupyter in /home/circleci/project/uvcdat-testdata
error: pathspec 'boxfill_widgets_jupyter' did not match any file(s) known to git.
FAILED...cmd: ['git', 'checkout', 'boxfill_widgets_jupyter']
Exited with code 1
```

We should probably add an option to allow to fall back on default branch and issue a warning

### PR DESCRIPTION
**Pull request by doutriaux1**
fix #10 
@muryanto1 I think the test will need tweaks, do you mind helping with this when you get a chance?

### CODE REVIEW

**Comment by muryanto1** [comment]
Charles, let me know if my update to the code looks okay to merge.

**Comment by muryanto1** [comment]
Charles, I do feel that the default value of --baselines-fallback-on-master should be True instead of False (which is what you had it first).

**Comment by doutriaux1** [comment]
@muryanto1 I was thinking so too. But ince right now it fails if the branch does not exit, I didn't want to change the current behaviour. Feel free to change this, the issue is that then passing the option would mean "no" so we should change the option to name to omething else like "--no-baseline-fallback-on-master"

**Comment by muryanto1** [comment]
If we keep the option --baselines-fallback-on-master, and default to be false, then when we work on a branch, we need to specify that option in .circleci/config.yml, otherwise our build cannot pass unless we have that branch name for uvcdat-testdata.  Then, it defeats the purpose of having this new option.
If we change the option to be --no-baselines-fallback-on-master, I feel that it is counter intuitive.
One option is to run run_tests.py with --baselines-fallback-on-master in .circleci/config.yml.   Is that okay?

**Comment by doutriaux1** [comment]
@muryanto1 why is using `--no-baselines-fallback-on-master` to turn off the fallback on master, counter intuitive? That makes the default the behavior what we want (falling back on master)

**Comment by muryanto1** [comment]
do you mean to have "--no-baselines-fallback-on-master " option, and default set to false?
so when we run run_tests.py w/out the option, we will fall back to master if the branch does not exist for uvcdat-testdata.

**Comment by doutriaux1** [comment]
@muryanto1 yes exactly.

**Comment by muryanto1** [comment]
ok, updated the code to have "--no-baselines-fallback-on-master " option, and default set to false,
and updated the unit test as well. Let me know if I can merge.

**Pull request merged**
